//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryCE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryCE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api-dev-revizor.apptimizm.pro.
        /// </summary>
        internal static string APIDomain {
            get {
                return ResourceManager.GetString("APIDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/product.
        /// </summary>
        internal static string APIProduct {
            get {
                return ResourceManager.GetString("APIProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/project.
        /// </summary>
        internal static string APIProject {
            get {
                return ResourceManager.GetString("APIProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/sync/get-project-data.
        /// </summary>
        internal static string APISync {
            get {
                return ResourceManager.GetString("APISync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/terminal.
        /// </summary>
        internal static string APITerminal {
            get {
                return ResourceManager.GetString("APITerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудалось загрузить данные с Веб сервиса .
        /// </summary>
        internal static string ErrorCanNotLoadData {
            get {
                return ResourceManager.GetString("ErrorCanNotLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите проект.
        /// </summary>
        internal static string ErrorLoginChooseProject {
            get {
                return ResourceManager.GetString("ErrorLoginChooseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP адрес некорректный.
        /// </summary>
        internal static string ErrorLoginInvalidIpAddress {
            get {
                return ResourceManager.GetString("ErrorLoginInvalidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP адресс не заполнен.
        /// </summary>
        internal static string ErrorLoginIPAddressIsNull {
            get {
                return ResourceManager.GetString("ErrorLoginIPAddressIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string ProoductsLimit {
            get {
                return ResourceManager.GetString("ProoductsLimit", resourceCulture);
            }
        }
    }
}
